//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeProjectHour2
    {
        public int EmployeeId { get; set; }
        public int ProjectId { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Hours { get; set; }
    }
}
